function(detect_nvcc_version NVCC_VERSION)
cmake_parse_arguments(ARG "" "REQUIRED" "" ${ARGN})

execute_process(COMMAND nvcc --version 
    OUTPUT_VARIABLE NVCC_VERSION_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE)

string(REGEX MATCH "V[0-9]+\\.[0-9]+\\.[0-9]+" NVCC_VERSION_STRING ${NVCC_VERSION_OUTPUT})
string(REGEX REPLACE "V" "" NVCC_VERSION_NUMS ${NVCC_VERSION_STRING})

string(REPLACE "." ";" NVCC_VERSION_LIST ${NVCC_VERSION_NUMS})
list(GET NVCC_VERSION_LIST 0 NVCC_VERSION_MAJOR)
list(GET NVCC_VERSION_LIST 1 NVCC_VERSION_MINOR)

set(NVCC_VERSION "${NVCC_VERSION_MAJOR}.${NVCC_VERSION_MINOR}" PARENT_SCOPE)
endfunction()